# Generated by Django 5.2.3 on 2025-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_roll_number_student_admission_date_and_more'),
        ('students', '0003_populate_student_data'),
    ]

    operations = [
    ]
